name: Android Debug APK (Mobile)

on:
  workflow_dispatch: {}
  push:
    branches: [ main, develop ]
    paths:
      - 'mobile/**'

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Prebuild Android
        run: npx expo prebuild --platform android --non-interactive

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: safesteps-debug-apk
          path: mobile/android/app/build/outputs/apk/debug/*.apk
